name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Check if VPS is up
      run: |
        echo "Checking if VPS is reachable..."
        if ! nc -zvw3 ${{ secrets.SSH_HOST }} ${{ secrets.SSH_PORT }}; then
          echo "VPS is down or unreachable. Stopping deployment."
          exit 1
        fi
        echo "VPS is online, proceeding with deployment."

    - name: Add SSH Private Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }}  >> ~/.ssh/known_hosts

    
    - name: Deploy using ssh
      uses: fabienOVH/action-deploy-vps-ovhcloud@v1.0.0
      with:
        ssh_host: ${{ secrets.SSH_HOST }}:${{ secrets.SSH_PORT }}
        ssh_user: ${{ secrets.SSH_USER }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        site_path: ${{ secrets.WORK_DIR }}
