name: Build Angular App

on:
  push:
    branches: [main]

jobs:
  build-angular:
    runs-on: debian-latest

    steps:

      - name: Retrieved Branche
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4.2.0
        with: 
          node-versoin: 10.8.3

      - name:  Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        
